
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashis
 */
public class systemAdmin extends javax.swing.JFrame {

    /**
     * Creates new form systemAdmin
     */
    public systemAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        roleTxt = new javax.swing.JComboBox<>();
        createTxt = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        dAddBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dNameTxt = new javax.swing.JTextField();
        dHospitalTxt = new javax.swing.JTextField();
        dRFVTxt = new javax.swing.JTextField();
        dPulseRateTxt = new javax.swing.JTextField();
        dOxygenLevelTxt = new javax.swing.JTextField();
        dDiagnosisTxt = new javax.swing.JTextField();
        signoutBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pPatientTable = new javax.swing.JTable();
        pUpdateBtn = new javax.swing.JButton();
        pAddBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pNameTxt = new javax.swing.JTextField();
        pDoctorTxt = new javax.swing.JTextField();
        pHospitalTxt = new javax.swing.JTextField();
        pCommunityTxt = new javax.swing.JTextField();
        signoutBtn1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pCityTxt = new javax.swing.JTextField();
        pDateTxt = new javax.swing.JTextField();
        pTimeTxt = new javax.swing.JTextField();
        pRFVTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        pGenderTxt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cCommunityTable = new javax.swing.JTable();
        cAddBtn = new javax.swing.JButton();
        cDeleteBtn = new javax.swing.JButton();
        cUpdateBtn = new javax.swing.JButton();
        cCommunityTxt = new javax.swing.JTextField();
        cCityTxt = new javax.swing.JTextField();
        cHospitalTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cHouseTxt = new javax.swing.JTextField();
        signoutBtn3 = new javax.swing.JButton();
        cPersonTxt = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hHospitalTable = new javax.swing.JTable();
        signoutBtn2 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        hNameTxt = new javax.swing.JTextField();
        hCommunityTxt = new javax.swing.JTextField();
        hNumberTxt = new javax.swing.JTextField();
        hEmailTxt = new javax.swing.JTextField();
        hPersonTxt = new javax.swing.JComboBox<>();
        hAddBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CREATE USER");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Username");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Password");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Role");

        roleTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roleTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Patient", "SystemAdmin", "CommunityAdmin", "HospitalAdmin" }));

        createTxt.setBackground(new java.awt.Color(51, 255, 51));
        createTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        createTxt.setText("CREATE");
        createTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTxtActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Role"
            }
        ));
        jScrollPane5.setViewportView(userTable);

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\admin.png")); // NOI18N
        jLabel38.setText("jLabel13");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameTxt)
                                .addComponent(passwordTxt)
                                .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(createTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(createTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ADD USER", jPanel5);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        doctorTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientName", "Hospital", "RFV", "PulseRate", "OxygenLevel", "Diagnosis"
            }
        ));
        doctorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctorTable);

        updateBtn.setBackground(new java.awt.Color(255, 255, 153));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\update.png")); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        dAddBtn.setBackground(new java.awt.Color(153, 255, 153));
        dAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dAddBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\add2.png")); // NOI18N
        dAddBtn.setText("ADD");
        dAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAddBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PatientName");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hospital");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("RFV");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PulseRate");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("OxygenLevel");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Diagnosis");

        signoutBtn.setBackground(new java.awt.Color(255, 0, 0));
        signoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\exit.png")); // NOI18N
        signoutBtn.setText("SignOut");
        signoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBtnActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Checkup ");

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\admin.png")); // NOI18N
        jLabel37.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(dAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(62, 62, 62)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(dNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dRFVTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dPulseRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dDiagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dOxygenLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dDiagnosisTxt, dHospitalTxt, dNameTxt, dOxygenLevelTxt, dPulseRateTxt, dRFVTxt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dRFVTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dPulseRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dOxygenLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dDiagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("DOCTOR", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        pPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Doctor", "Hospital", "Community", "City", "Date", "Time", "Gender", "RFV"
            }
        ));
        pPatientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPatientTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pPatientTable);

        pUpdateBtn.setBackground(new java.awt.Color(255, 255, 153));
        pUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pUpdateBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\update.png")); // NOI18N
        pUpdateBtn.setText("Update");
        pUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pUpdateBtnActionPerformed(evt);
            }
        });

        pAddBtn.setBackground(new java.awt.Color(153, 255, 153));
        pAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pAddBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\add2.png")); // NOI18N
        pAddBtn.setText("ADD");
        pAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Doctor");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Hospital");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Community");

        signoutBtn1.setBackground(new java.awt.Color(255, 0, 0));
        signoutBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoutBtn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\exit.png")); // NOI18N
        signoutBtn1.setText("SignOut");
        signoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBtn1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Date");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Time");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Gender");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("RFV");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("City");

        pDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDateTxtActionPerformed(evt);
            }
        });

        pRFVTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pRFVTxtActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("Book Appointment");

        pGenderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Search");

        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtKeyPressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\admin.png")); // NOI18N
        jLabel15.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pDoctorTxt)
                                            .addComponent(pHospitalTxt)
                                            .addComponent(pCommunityTxt)
                                            .addComponent(pCityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                        .addGap(102, 102, 102))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(pNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addGap(109, 109, 109)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pTimeTxt)
                                            .addComponent(pRFVTxt)
                                            .addComponent(pDateTxt)
                                            .addComponent(pGenderTxt, 0, 194, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(pAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(pUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(signoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pUpdateBtn))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addComponent(pDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(pDoctorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addComponent(pTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(pGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pCommunityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(pRFVTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(pCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(pAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        jTabbedPane1.addTab("PATIENT", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        cCommunityTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cCommunityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "House", "Person", "Community", "City", "Hospital"
            }
        ));
        cCommunityTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cCommunityTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(cCommunityTable);

        cAddBtn.setBackground(new java.awt.Color(0, 255, 0));
        cAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cAddBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\add2.png")); // NOI18N
        cAddBtn.setText("ADD");
        cAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddBtnActionPerformed(evt);
            }
        });

        cDeleteBtn.setBackground(new java.awt.Color(255, 153, 153));
        cDeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cDeleteBtn.setText("Delete");
        cDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeleteBtnActionPerformed(evt);
            }
        });

        cUpdateBtn.setBackground(new java.awt.Color(255, 255, 153));
        cUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cUpdateBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\update.png")); // NOI18N
        cUpdateBtn.setText("Update");
        cUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUpdateBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("House");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Person");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Community:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("City");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Hospital");

        signoutBtn3.setBackground(new java.awt.Color(255, 0, 0));
        signoutBtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoutBtn3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\exit.png")); // NOI18N
        signoutBtn3.setText("SignOut");
        signoutBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBtn3ActionPerformed(evt);
            }
        });

        cPersonTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Patient", "Visitor" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Community");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\admin.png")); // NOI18N
        jLabel14.setText("jLabel13");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(cDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cHouseTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(cCommunityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(cCityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(cHospitalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(cPersonTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(signoutBtn3)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(405, 405, 405))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cCityTxt, cCommunityTxt, cHospitalTxt, cHouseTxt});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cUpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(cHouseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cPersonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cCommunityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(cAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CommunityAdmin", jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        hHospitalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hopital Name", "Community", "Person", "Number", "Email"
            }
        ));
        jScrollPane3.setViewportView(hHospitalTable);

        signoutBtn2.setBackground(new java.awt.Color(255, 0, 0));
        signoutBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoutBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        signoutBtn2.setText("SignOut");
        signoutBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBtn2ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Hospital Name");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Community");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Person");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Number");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setText("Email");

        hCommunityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hCommunityTxtActionPerformed(evt);
            }
        });

        hEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hEmailTxtActionPerformed(evt);
            }
        });

        hPersonTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Patient", "Visitor" }));

        hAddBtn.setBackground(new java.awt.Color(153, 255, 153));
        hAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hAddBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\add2.png")); // NOI18N
        hAddBtn.setText("ADD");
        hAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hAddBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Hospital Admin");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashis\\Documents\\admin.png")); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(signoutBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hEmailTxt)
                            .addComponent(hNumberTxt)
                            .addComponent(hCommunityTxt)
                            .addComponent(hNameTxt)
                            .addComponent(hPersonTxt, 0, 221, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(hAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signoutBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(hNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(hCommunityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(hPersonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(hNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(hEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hAddBtn)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HospitalAdmin", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
         setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_signoutBtnActionPerformed

    private void signoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBtn1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_signoutBtn1ActionPerformed

    private void signoutBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBtn2ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_signoutBtn2ActionPerformed

    private void signoutBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBtn3ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_signoutBtn3ActionPerformed

    private void createTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTxtActionPerformed
        // TODO add your handling code here:
        String role = roleTxt.getSelectedItem().toString();
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();
        
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            JOptionPane.showMessageDialog(null, "User successfully added!");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");

      
    }
         User_table();
        
    }//GEN-LAST:event_createTxtActionPerformed

    private void dAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAddBtnActionPerformed
        // TODO add your handling code here:
        String pName = dNameTxt.getText();
        String hospital = dHospitalTxt.getText();
        String RFV = dRFVTxt.getText();
        String pulseRate = dPulseRateTxt.getText();
        String oxygenLevel = dOxygenLevelTxt.getText();
        String diagnosis = dDiagnosisTxt.getText();
       

        

        
        DCheckup.DCreateCheckup(pName,hospital,RFV,pulseRate,oxygenLevel,diagnosis);
        
        dNameTxt.setText("");
        dHospitalTxt.setText("");
        dRFVTxt.setText("");
        dPulseRateTxt.setText("");
        dOxygenLevelTxt.setText("");
        dDiagnosisTxt.setText("");
        
            d_doctor_table();
    }//GEN-LAST:event_dAddBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tb1Model = (DefaultTableModel)doctorTable.getModel();
      
      if(doctorTable.getSelectedRowCount()==1){
          tb1Model.removeRow(doctorTable.getSelectedRow());
      }else{
          if(doctorTable.getRowCount()==0){
              JOptionPane.showMessageDialog(null,"Table is Empty");
          } else{
              JOptionPane.showMessageDialog(null,"Please Select Single Row");
          }
      }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)doctorTable.getModel();
        if(doctorTable.getSelectedRowCount()== 1){
            String name = dNameTxt.getText();
            String hosp = dHospitalTxt.getText();
            String RFV = dRFVTxt.getText();
            String pulse = dPulseRateTxt.getText();
            String oxy = dOxygenLevelTxt.getText();
            String diagnosis = dDiagnosisTxt.getText();
            
            
            
            tb1Model.setValueAt(name,doctorTable.getSelectedRow(), 0);
            tb1Model.setValueAt(hosp,doctorTable.getSelectedRow(), 1);
            tb1Model.setValueAt(RFV,doctorTable.getSelectedRow(), 2);
            tb1Model.setValueAt(pulse,doctorTable.getSelectedRow(), 3);
            tb1Model.setValueAt(oxy,doctorTable.getSelectedRow(), 4);
            tb1Model.setValueAt(diagnosis,doctorTable.getSelectedRow(), 5);
            
            
            JOptionPane.showMessageDialog(this,"Update Successfully");

            
        }else{
            if(doctorTable.getRowCount()== 0){
                     JOptionPane.showMessageDialog(this,"Table is Empty");

            }else{
                     JOptionPane.showMessageDialog(this,"Please Select Single Row for Update");

            }
        }
           
    }//GEN-LAST:event_updateBtnActionPerformed

    private void doctorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)doctorTable.getModel();
        
        String tb1pName = tb1Model.getValueAt(doctorTable.getSelectedRow(),0).toString();
        String tb1hosp = tb1Model.getValueAt(doctorTable.getSelectedRow(),1).toString();
        String tb1RFV = tb1Model.getValueAt(doctorTable.getSelectedRow(),2).toString();
        String tb1pulse = tb1Model.getValueAt(doctorTable.getSelectedRow(),3).toString();
        String tb1oxyLvl = tb1Model.getValueAt(doctorTable.getSelectedRow(),4).toString();
        String tb1Diagnosis = tb1Model.getValueAt(doctorTable.getSelectedRow(),5).toString();
       
        
        dNameTxt.setText(tb1pName);
        dHospitalTxt.setText(tb1hosp);
        dRFVTxt.setText(tb1RFV);
        dPulseRateTxt.setText(tb1pulse);
        dOxygenLevelTxt.setText(tb1oxyLvl);
        dDiagnosisTxt.setText(tb1Diagnosis);
    }//GEN-LAST:event_doctorTableMouseClicked

    private void pRFVTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pRFVTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pRFVTxtActionPerformed

    private void pDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pDateTxtActionPerformed

    
    public class Appointment{
        
        
        public static void CreateAppointment(String name, String doctor, String hospital, String community, String city, String date, String time, String gender, String RFV){
            
             try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String query = "INSERT INTO hospitalsystem.patient (Name,Doctor,Hospital,Community,City,Date,Time,Gender,RFV) values(?,?,?,?,?,?,?,?,?)";
            
            java.sql.PreparedStatement preparedStmt = connection.prepareStatement(query);
            preparedStmt.setString(1,name);
            preparedStmt.setString(2,doctor);
            preparedStmt.setString(3,hospital);
            preparedStmt.setString(4,community);
            preparedStmt.setString(5,city);
            preparedStmt.setString(6,date);
            preparedStmt.setString(7,time);
            preparedStmt.setString(8,gender);
            preparedStmt.setString(9,RFV);

            preparedStmt.execute();
                        JOptionPane.showMessageDialog(null,"NAme Added");

             connection.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"please add data in correct format!");
            
            

    
    }                     
//            

        }
    
    } 
    
    
    private void pAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAddBtnActionPerformed
        // TODO add your handling code here:
        String name = pNameTxt.getText();
        String doctor = pDoctorTxt.getText();
        String hospital = pHospitalTxt.getText();
        String community = pCommunityTxt.getText();
        String city = pCityTxt.getText();
        String date = pDateTxt.getText();
        String time = pTimeTxt.getText();
        String gender = (String) pGenderTxt.getSelectedItem();
        String RFV = pRFVTxt.getText();

        

        
        Appointment.CreateAppointment(name,doctor,hospital,community,city,date,time,gender,RFV);
        
        pNameTxt.setText("");
        pDoctorTxt.setText("");
        pHospitalTxt.setText("");
        pCommunityTxt.setText("");
        pCityTxt.setText("");
        pDateTxt.setText("");
        pTimeTxt.setText("");
        pGenderTxt.setSelectedItem("");
        pRFVTxt.setText("");
            patient_table();
    }//GEN-LAST:event_pAddBtnActionPerformed

    private void pUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pUpdateBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tb1Model = (DefaultTableModel)pPatientTable.getModel();
        if(pPatientTable.getSelectedRowCount()== 1){
            String name = pNameTxt.getText();
            String doctor = pDoctorTxt.getText();
            String hospital = pHospitalTxt.getText();
            String community = pCommunityTxt.getText();
            String city = pCityTxt.getText();
            String date = pDateTxt.getText();
            String time = pTimeTxt.getText();
            String gender = (String) pGenderTxt.getSelectedItem();
            String RFV = pRFVTxt.getText();
            
            
            tb1Model.setValueAt(name,pPatientTable.getSelectedRow(), 0);
            tb1Model.setValueAt(doctor,pPatientTable.getSelectedRow(), 1);
            tb1Model.setValueAt(hospital,pPatientTable.getSelectedRow(), 2);
            tb1Model.setValueAt(community,pPatientTable.getSelectedRow(), 3);
            tb1Model.setValueAt(city,pPatientTable.getSelectedRow(), 4);
            tb1Model.setValueAt(date,pPatientTable.getSelectedRow(), 5);
            tb1Model.setValueAt(time,pPatientTable.getSelectedRow(), 6);
            tb1Model.setValueAt(gender,pPatientTable.getSelectedRow(), 7);
            tb1Model.setValueAt(RFV,pPatientTable.getSelectedRow(), 8);
            
            JOptionPane.showMessageDialog(this,"Update Successfully");

            
        }else{
            if(pPatientTable.getRowCount()== 0){
                     JOptionPane.showMessageDialog(this,"Table is Empty");

            }else{
                     JOptionPane.showMessageDialog(this,"Please Select Single Row for Update");

            }
        }
    }//GEN-LAST:event_pUpdateBtnActionPerformed

    private void pPatientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPatientTableMouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel tb1Model = (DefaultTableModel)pPatientTable.getModel();
        
        String tb1Name = tb1Model.getValueAt(pPatientTable.getSelectedRow(),0).toString();
        String tb1Doctor = tb1Model.getValueAt(pPatientTable.getSelectedRow(),1).toString();
        String tb1Hospital = tb1Model.getValueAt(pPatientTable.getSelectedRow(),2).toString();
        String tb1Community = tb1Model.getValueAt(pPatientTable.getSelectedRow(),3).toString();
        String tb1City = tb1Model.getValueAt(pPatientTable.getSelectedRow(),4).toString();
        String tb1Date = tb1Model.getValueAt(pPatientTable.getSelectedRow(),5).toString();
        String tb1Time = tb1Model.getValueAt(pPatientTable.getSelectedRow(),6).toString();
        String tb1Gender = tb1Model.getValueAt(pPatientTable.getSelectedRow(),7).toString();
        String tb1RFV = tb1Model.getValueAt(pPatientTable.getSelectedRow(),8).toString();
        
        pNameTxt.setText(tb1Name);
        pDoctorTxt.setText(tb1Doctor);
        pHospitalTxt.setText(tb1Hospital);
        pCommunityTxt.setText(tb1Community);
        pCityTxt.setText(tb1City);
        pDateTxt.setText(tb1Date);
        pTimeTxt.setText(tb1Time);
        pGenderTxt.setSelectedItem(tb1Gender);
        pRFVTxt.setText(tb1RFV);
    }//GEN-LAST:event_pPatientTableMouseClicked

    private void searchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)pPatientTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        pPatientTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxt.getText().trim()));
    }//GEN-LAST:event_searchTxtKeyPressed

    
    public class Community{
        
        
        public static void CreateCommunity(String house, String person, String community, String city, String hospital){
            
             try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String query = "INSERT INTO hospitalsystem.community (House,Person,Community,City,Hospital) values(?,?,?,?,?)";
            
            java.sql.PreparedStatement preparedStmt = connection.prepareStatement(query);
            preparedStmt.setString(1,house);
            preparedStmt.setString(2,person);
            preparedStmt.setString(3,community);
            preparedStmt.setString(4,city);
            preparedStmt.setString(5,hospital);
           

            preparedStmt.execute();
                        JOptionPane.showMessageDialog(null,"Details Added");

             connection.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"please add data in correct format!");
            
            

    
    }                     
//            

        }
    
    } 
    
    
    
    private void cAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddBtnActionPerformed
        // TODO add your handling code here:
        
         String house = cHouseTxt.getText();
        String person = (String) cPersonTxt.getSelectedItem();
        String community = cCommunityTxt.getText();
        String city = cCityTxt.getText();
        String hospital = cHospitalTxt.getText();

        
         Community.CreateCommunity(house,person,community,city,hospital);  
        
        
      //  JOptionPane.showMessageDialog(this,"New Employ details Added");
        
        
        cHouseTxt.setText("");
        cPersonTxt.setSelectedItem("");
        cCommunityTxt.setText("");
        cCityTxt.setText("");
        cHospitalTxt.setText("");
        community_table();
    }//GEN-LAST:event_cAddBtnActionPerformed

    private void cUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUpdateBtnActionPerformed
        // TODO add your handling code here:
        
          DefaultTableModel tb1Model = (DefaultTableModel)cCommunityTable.getModel();
        if(cCommunityTable.getSelectedRowCount()== 1){
            String house = cHouseTxt.getText();
            String person = (String) cPersonTxt.getSelectedItem();
            String community = cCommunityTxt.getText();
            String city = cCityTxt.getText();
            String hospital = cHospitalTxt.getText();
            
            
            
            tb1Model.setValueAt(house,cCommunityTable.getSelectedRow(), 0);
            tb1Model.setValueAt(person,cCommunityTable.getSelectedRow(), 1);
            tb1Model.setValueAt(community,cCommunityTable.getSelectedRow(), 2);
            tb1Model.setValueAt(city,cCommunityTable.getSelectedRow(), 3);
            tb1Model.setValueAt(hospital,cCommunityTable.getSelectedRow(), 4);
            
            
            JOptionPane.showMessageDialog(this,"Update Successfully");

            
        }else{
            if(cCommunityTable.getRowCount()== 0){
                     JOptionPane.showMessageDialog(this,"Table is Empty");

            }else{
                     JOptionPane.showMessageDialog(this,"Please Select Single Row for Update");

            }
        }
    }//GEN-LAST:event_cUpdateBtnActionPerformed

    private void cCommunityTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCommunityTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)cCommunityTable.getModel();
        
        String tb1house = tb1Model.getValueAt(cCommunityTable.getSelectedRow(),0).toString();
        String tb1person = tb1Model.getValueAt(cCommunityTable.getSelectedRow(),1).toString();
        String tb1community = tb1Model.getValueAt(cCommunityTable.getSelectedRow(),2).toString();
        String tb1city = tb1Model.getValueAt(cCommunityTable.getSelectedRow(),3).toString();
        String tb1hospital = tb1Model.getValueAt(cCommunityTable.getSelectedRow(),4).toString();
       
        
        cHouseTxt.setText(tb1house);
        cPersonTxt.setSelectedItem(tb1person);
        cCommunityTxt.setText(tb1community);
        cCityTxt.setText(tb1city);
        cHospitalTxt.setText(tb1hospital);
    }//GEN-LAST:event_cCommunityTableMouseClicked

    private void cDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeleteBtnActionPerformed
        // TODO add your handling code here:
           DefaultTableModel tb1Model = (DefaultTableModel)cCommunityTable.getModel();
      
      if(cCommunityTable.getSelectedRowCount()==1){
          tb1Model.removeRow(cCommunityTable.getSelectedRow());
      }else{
          if(cCommunityTable.getRowCount()==0){
              JOptionPane.showMessageDialog(null,"Table is Empty");
          } else{
              JOptionPane.showMessageDialog(null,"Please Select Single Row");
          }
      }
    }//GEN-LAST:event_cDeleteBtnActionPerformed

    private void hCommunityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hCommunityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hCommunityTxtActionPerformed

    private void hEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hEmailTxtActionPerformed

     public class Hospital{
        
        
        public static void CreateHospital(String Hospitalname, String community, String person, String number,String email  ){
            
             try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String query = "INSERT INTO hospitalsystem.hospital (HospitalName,Community,Person,Number,Email) values(?,?,?,?,?)";
            
            java.sql.PreparedStatement preparedStmt = connection.prepareStatement(query);
            preparedStmt.setString(1,Hospitalname);
            preparedStmt.setString(2,community);
            preparedStmt.setString(3,person);
            preparedStmt.setString(4,number);
            preparedStmt.setString(5,email);
            

            preparedStmt.execute();
                        JOptionPane.showMessageDialog(null,"NAme Added");

             connection.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"please add data in correct format!");
            
            

    
    }                     
//            try{
//                Connection connection = ConnectionProvider.Connect();
//                Statement statement = connection.createStatement();
//                
//            }
//            catch(Exception e){
//                
//            }

        }
    
    } 
    
    
    
    private void hAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hAddBtnActionPerformed
        // TODO add your handling code here:
        
        String Hospitalname = hNameTxt.getText();
        String community = hCommunityTxt.getText();
        String number = hNumberTxt.getText();
        String person = (String) hPersonTxt.getSelectedItem();
        String email = hEmailTxt.getText();

        if(hNameTxt.getText().isEmpty()|| hCommunityTxt.getText().isEmpty()||hNumberTxt.getText().isEmpty()|| hEmailTxt.getText().isEmpty()          ){
                 JOptionPane.showMessageDialog(null, "Plz Enter Details!");

        
        } else{

        
         Hospital.CreateHospital(Hospitalname,community,person,number,email);
         Hospital_table();
        }
        hNameTxt.setText("");
        hCommunityTxt.setText("");
        
        hNumberTxt.setText("");
        hPersonTxt.setSelectedItem("");
        hEmailTxt.setText("");
        
         
    }//GEN-LAST:event_hAddBtnActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    
    public void Hospital_table(){
                    try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String sql = "SELECT * FROM hospitalsystem.hospital";
           // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
           // JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String hospitalName = rs.getString("HospitalName");
                String community = rs.getString("Community");
                String city = rs.getString("Person");
                String person = rs.getString("Number");
                String address = rs.getString("Email");
                
                String tbData[] = {hospitalName,community,city,person,address};
                DefaultTableModel tb1Model = (DefaultTableModel)hHospitalTable.getModel();
                
                tb1Model.addRow(tbData);
                 System.out.println("Ashish gg");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");

    
    }           
    }
    
    
    public void community_table(){
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String sql = "SELECT * FROM hospitalsystem.community;";
           // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            //JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String house = rs.getString("House");
                String person = rs.getString("Person");
                String community = rs.getString("Community");
                String city = rs.getString("City");
                String hospital = rs.getString("Hospital");
                
                
                String tbData[] = {house,person,community,city,hospital};
                DefaultTableModel tb1Model = (DefaultTableModel)cCommunityTable.getModel();
                
                tb1Model.addRow(tbData);
                 System.out.println("Ashish well done");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");

    
    }                                 
    }
    
    public void patient_table(){
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String sql = "SELECT * FROM hospitalsystem.patient;";
           // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String name = rs.getString("Name");
                String doctor = rs.getString("Doctor");
                String hospital = rs.getString("Hospital");
                String community = rs.getString("Community");
                String city = rs.getString("City");
                String date = rs.getString("Date");
                String time = rs.getString("Time");
                String gender = rs.getString("Gender");
                String RFV = rs.getString("RFV");

                
                String tbData[] = {name,doctor,hospital,community,city,date,time,gender,RFV};
                DefaultTableModel tb1Model = (DefaultTableModel)pPatientTable.getModel();
                
                tb1Model.addRow(tbData);
                 System.out.println("Ashish well done");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");

    
    }                                 
    }
    
    
    public class DCheckup{
        
        
        public static void DCreateCheckup(String pName, String hospital, String RFV, String pulseRate, String oxygenLevel, String diagnosis){
            
             try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String query = "INSERT INTO hospitalsystem.doctor (PatientName,Hospital,RFV,PulseRate,OxygenLevel,Diagnosis) values(?,?,?,?,?,?)";
            
            java.sql.PreparedStatement preparedStmt = connection.prepareStatement(query);
            preparedStmt.setString(1,pName);
            preparedStmt.setString(2,hospital);
            preparedStmt.setString(3,RFV);
            preparedStmt.setString(4,pulseRate);
            preparedStmt.setString(5,oxygenLevel);
            preparedStmt.setString(6,diagnosis);
           

            preparedStmt.execute();
                        JOptionPane.showMessageDialog(null,"NAme Added");

             connection.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"please add data in correct format!");
            
            

    
    }                     
//            

        }
    
    }
    
    public void d_doctor_table(){
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String sql = "SELECT * FROM hospitalsystem.doctor;";
           // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String pName = rs.getString("PatientName");
                String hospital = rs.getString("Hospital");
                String RFV = rs.getString("RFV");
                String pulseRate = rs.getString("PulseRate");
                String oxygenLevel = rs.getString("OxygenLevel");
                String diagnosis = rs.getString("Diagnosis");
                
                
                String tbData[] = {pName,hospital,RFV,pulseRate,oxygenLevel,diagnosis};
                DefaultTableModel tb1Model = (DefaultTableModel)doctorTable.getModel();
                
                tb1Model.addRow(tbData);
                 System.out.println("Ashish well done");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");

    
    }                                 
    }
    
    
       public void User_table(){
                    try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalsystem", "root", "root");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
             String sql = "SELECT * FROM hospitalsystem.login";

           // String sql = "SELECT * FROM hospitalsystem.login";
           // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            //JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String user = rs.getString("username");
                String password = rs.getString("password");
                String role = rs.getString("role");
               
                
                String tbData[] = {user,password,role};
                DefaultTableModel tb1Model = (DefaultTableModel)userTable.getModel();
                
                tb1Model.addRow(tbData);
                 System.out.println("Ashish gg");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");

    
    }           
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new systemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cAddBtn;
    private javax.swing.JTextField cCityTxt;
    private javax.swing.JTable cCommunityTable;
    private javax.swing.JTextField cCommunityTxt;
    private javax.swing.JButton cDeleteBtn;
    private javax.swing.JTextField cHospitalTxt;
    private javax.swing.JTextField cHouseTxt;
    private javax.swing.JComboBox<String> cPersonTxt;
    private javax.swing.JButton cUpdateBtn;
    private javax.swing.JButton createTxt;
    private javax.swing.JButton dAddBtn;
    private javax.swing.JTextField dDiagnosisTxt;
    private javax.swing.JTextField dHospitalTxt;
    private javax.swing.JTextField dNameTxt;
    private javax.swing.JTextField dOxygenLevelTxt;
    private javax.swing.JTextField dPulseRateTxt;
    private javax.swing.JTextField dRFVTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable doctorTable;
    private javax.swing.JButton hAddBtn;
    private javax.swing.JTextField hCommunityTxt;
    private javax.swing.JTextField hEmailTxt;
    private javax.swing.JTable hHospitalTable;
    private javax.swing.JTextField hNameTxt;
    private javax.swing.JTextField hNumberTxt;
    private javax.swing.JComboBox<String> hPersonTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton pAddBtn;
    private javax.swing.JTextField pCityTxt;
    private javax.swing.JTextField pCommunityTxt;
    private javax.swing.JTextField pDateTxt;
    private javax.swing.JTextField pDoctorTxt;
    private javax.swing.JComboBox<String> pGenderTxt;
    private javax.swing.JTextField pHospitalTxt;
    private javax.swing.JTextField pNameTxt;
    private javax.swing.JTable pPatientTable;
    private javax.swing.JTextField pRFVTxt;
    private javax.swing.JTextField pTimeTxt;
    private javax.swing.JButton pUpdateBtn;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JComboBox<String> roleTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton signoutBtn;
    private javax.swing.JButton signoutBtn1;
    private javax.swing.JButton signoutBtn2;
    private javax.swing.JButton signoutBtn3;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
